version: '3.7'

services:

  app:
    build: .
    command: make run
    env_file:
      - .env
    restart: always

  redis:
    image: 'redis:alpine'
    volumes:
      - cache:/data
    restart: always

  mongodb:
    image: mongo:5.0
    volumes:
      - mongo:/data/db
    env_file:
      - .env
    restart: always

volumes:
  cache:
  mongo: