from aiogram.fsm.state import State, StatesGroup

class MyAnnouncementEditState(StatesGroup):
    house_edit = State()
    section_edit = State()
    corps_edit = State()
    floor_edit = State()
    room_count_edit = State()
    price_edit = State()
    area_edit = State()
    kitchen_area_edit = State()
    balcony_edit = State()
    commission_edit = State()
    district_edit = State()
    micro_district_edit = State()
    live_condition_edit = State()
    planning_edit = State()
    scheme_edit = State()
    photo_gallery_edit = State()
    location_edit = State()
    confirm = State()
